apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: workshop
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: yout-domain-name
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
