apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myIngress
  namespace: workshop
spec:
  rules:
    - host: pfa 
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
